version: 2.1

jobs: 
  buid-docker: 
    environment: 
      IMAGE_NAME: laclac0901/hello                     
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/devops-capstone
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest


workflows:
  default:
    jobs:
# CI
      - build-docker
      - unit-test
# CD
      - push-image
      - create-infrastructure
      - deploy      