apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - image: laclac0901/hello
        name: app
        ports: 
          - containerPort: 80
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"     