# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: app
#   name: app
# spec:
#   ports:
#   - name: "http"
#     port: 80
#     targetPort: 80
#   selector:
#     service: app
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    run: app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: app
